import { NextResponse } from "next/server";
import { getAdminSession, verifyAdminCsrf } from "../../../../lib/admin-auth";
import { deleteHallEnquiryFromAdmin, getHallEnquiry, updateHallEnquiryFromAdmin } from "../../../../lib/booking-store";
import { BookingValidationError, validateAdminHallEnquiry } from "../../../../lib/bookings";
import { notifyHallDecision } from "../../../../lib/email/notifications";
import { configuredSiteOrigin, isTrustedOrigin, noStoreJson, readLimitedFormData } from "../../../../lib/security";
export const runtime="nodejs";
const idPattern=/^hall_[A-Za-z0-9_-]{16,80}$/;
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const session=await getAdminSession("hall:read");if(!session)return noStoreJson({error:"Unauthorized"},{status:401});const {id}=await params;if(!idPattern.test(id))return noStoreJson({error:"Invalid hall enquiry reference"},{status:400});const hallEnquiry=await getHallEnquiry(id);return hallEnquiry?noStoreJson({hallEnquiry}):noStoreJson({error:"Hall enquiry not found"},{status:404});}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const form=await readLimitedFormData(request,32_000);const action=String(form.get("action")||"update");const permission=action==="delete"?"hall:delete":"hall:write";const session=await getAdminSession(permission);if(!session||!isTrustedOrigin(request)||!verifyAdminCsrf(session,String(form.get("csrf")||"")))return new NextResponse("Forbidden",{status:403});const {id}=await params;const validId=idPattern.test(id);if(action==="delete"){const deleted=validId?await deleteHallEnquiryFromAdmin(id,session.userId):false;return NextResponse.redirect(new URL(`/admin/hall-enquiries?update=${deleted?"deleted":"rejected"}`,configuredSiteOrigin(request)),303);}try{const updated=validId?await updateHallEnquiryFromAdmin(id,validateAdminHallEnquiry(Object.fromEntries(form)),session.userId):null;if(updated)await notifyHallDecision(updated);return NextResponse.redirect(new URL(`/admin/hall-enquiries?update=${updated?"success":"rejected"}`,configuredSiteOrigin(request)),303);}catch(error){const update=error instanceof BookingValidationError?"invalid":"rejected";return NextResponse.redirect(new URL(`/admin/hall-enquiries?update=${update}`,configuredSiteOrigin(request)),303);}}
